volumes:
  vault-init-data:
  vault-data-node1:
  vault-data-node2:

networks:
  super_services_network:
    driver: bridge

services:
  vault-node1:
    extends:
      file: template.yml
      service: vault-node-template
    container_name: vault-node1
    ports:
      - "8300:8200"    # API port
      - "8301:8201"    # Cluster (Raft) port
    environment:
      VAULT_API_ADDR: http://vault-node1:8200
      VAULT_CLUSTER_ADDR: http://vault-node1:8201
      VAULT_RAFT_NODE_ID: vault-node1
    volumes:
      - vault-data-node1:/vault/data

  vault-node2:
    extends:
      file: template.yml
      service: vault-node-template
    container_name: vault-node2
    ports:
      - "8400:8200"    # API port
      - "8401:8201"    # Cluster (Raft) port
    environment:
      VAULT_API_ADDR: http://vault-node2:8200
      VAULT_CLUSTER_ADDR: http://vault-node2:8201
      VAULT_RAFT_NODE_ID: vault-node2
    volumes:
      - vault-data-node2:/vault/data
    
  vault-init:
    image: curlimages/curl:latest
    container_name: vault-init
    depends_on:
      - vault-node1
    environment:
      - VAULT_NODE1_ADDR=http://vault-node1:8200
    volumes:
      - ./scripts:/vault/scripts
      - ./files:/vault/files
      - vault-init-data:/opt/vault/data
    entrypoint: ["/bin/sh", "/vault/scripts/init.sh"]
    networks:
      - super_services_network
    restart: "no"

  vault-unseal:
    image: curlimages/curl:latest
    container_name: vault-unseal
    depends_on:
      - vault-init
    environment:
      - VAULT_NODE1_ADDR=http://vault-node1:8200
      - VAULT_NODE2_ADDR=http://vault-node2:8200
    volumes:
      - ./scripts:/vault/scripts
      - ./files:/vault/files
      - vault-init-data:/opt/vault/data
    entrypoint: ["/bin/sh", "/vault/scripts/unseal.sh"]
    networks:
      - super_services_network
    restart: "no"

  vault-preload:
    image: curlimages/curl:latest
    container_name: vault-preload
    depends_on:
      - vault-unseal
    environment:
      - VAULT_NODE1_ADDR=http://vault-node1:8200
      # Optionally inject the token if you preload using it
      # - VAULT_ROOT_TOKEN=xxxxxx
    volumes:
      - ./scripts:/vault/scripts
      - ./files:/vault/files
      - vault-init-data:/opt/vault/data
    entrypoint: ["/bin/sh", "/vault/scripts/preload.sh"]
    networks:
      - super_services_network
    restart: "no"
