version: '3.9'

services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    environment:
      - VAULT_ENABLED=true
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - KEYCLOAK_URL=http://keycloak:8080
      - REALM=mono-services
      - DATABASE_URL=postgres://user:password@postgres:5432/super_services?sslmode=disable
      - REDIS_URL=redis://redis:6379
    container_name: auth
    ports:
      - "8000:8000"
    volumes:
      - ../../services/auth:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy  
      keycloak:
        condition: service_healthy
    networks:
      - super_services_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["air"]