version: '3.9'

services:
  gateway:
    build:
      context: ./cmd/gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your_jwt_secret
      - VAULT_ADDR=http://vault:8200  # <- Add Vault address if needed
    depends_on:
      vault: 
        condition: service_healthy
      auth:
        condition: service_healthy
      user:
        condition: service_healthy
      notification:
        condition: service_healthy
      billing:
        condition: service_healthy
      search:
        condition: service_healthy
    networks:
      - super_services_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    environment:
      - VAULT_ENABLED=true
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - KEYCLOAK_URL=http://keycloak:8080
      - REALM=mono-services
      - DATABASE_URL=postgres://user:password@postgres:5432/super_services?sslmode=disable
      - REDIS_URL=redis://redis:6379
    depends_on:
      gateway::
        condition: service_healthy
    networks:
      - super_services_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3