version: '3.9'
    
volumes:
  vault-init-data:
  vault_data_node1:
  vault_data_node2:

services:
  vault-node1:
    image: vault:1.15
    container_name: vault-node1
    ports:
      - "8200:8200"    # API port
      - "8201:8201"    # Cluster (Raft) port
    environment:
      VAULT_API_ADDR: http://vault-node1:8200
      VAULT_CLUSTER_ADDR: http://vault-node1:8201
      VAULT_RAFT_NODE_ID: vault-node1
    volumes:
      - vault_data_node1:/vault/data
      - ./deployments/vault/config:/vault/config
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      - super_services_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault-node2:
    image: vault:1.15
    container_name: vault-node2
    ports:
      - "8202:8200"    # API port
      - "8203:8201"    # Cluster (Raft) port
    environment:
      VAULT_API_ADDR: http://vault-node2:8200
      VAULT_CLUSTER_ADDR: http://vault-node2:8201
      VAULT_RAFT_NODE_ID: vault-node2
    volumes:
      - vault_data_node2:/vault/data
      - ./deployments/vault/config:/vault/config
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      - super_services_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  vault-init:
    image: curlimages/curl:latest
    container_name: vault-init
    environment:
      - VAULT_NODE1_ADDR=http://vault-node1:8200
    volumes:
      - ./scripts/vault:/scripts
      - vault-init-data:/vault
    entrypoint: ["/bin/sh", "/scripts/init.sh"]
    depends_on:
      - vault-node1
    networks:
      - super_services_network
    restart: "no"

  vault-unseal:
    image: curlimages/curl:latest
    container_name: vault-unseal
    environment:
      - VAULT_NODE1_ADDR=http://vault-node1:8200
      - VAULT_NODE2_ADDR=http://vault-node2:8200
    volumes:
      - ./scripts/vault:/scripts
      - vault-init-data:/vault
    entrypoint: ["/bin/sh", "/scripts/unseal.sh"]
    depends_on:
      - vault-init
    networks:
      - super_services_network
    restart: "no"

  vault-preload:
    image: curlimages/curl:latest
    container_name: vault-preload
    environment:
      - VAULT_NODE1_ADDR=http://vault-node1:8200
      # Optionally inject the token if you preload using it
      # - VAULT_ROOT_TOKEN=xxxxxx
    volumes:
      - ./scripts/vault:/scripts
      - vault-init-data:/vault
    entrypoint: ["/bin/sh", "/scripts/preload.sh"]
    depends_on:
      - vault-unseal
    networks:
      - super_services_network
    restart: "no"
